/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.kpastorcic11.forms;


import hr.kpastorcic11.factories.RepositoryFactory;
import hr.kpastorcic11.roles.User;
import hr.kpastorcic11.forms.interfaces.Loginable;
import hr.kpastorcic11.panels.AdminPanel;
import hr.kpastorcic11.panels.MoviePanel;
import hr.kpastorcic11.repositories.interfaces.RoleManager;
import hr.kpastorcic11.repositories.interfaces.UsersRepository;
import hr.kpastorcic11.roles.enums.Role;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author islan
 */
public class MainCinemaFrame extends javax.swing.JFrame implements Loginable {

    private int idUser;
    private UsersRepository repository;
    private RoleManager roleManager;
    /**
     * Creates new form NewJFrame
     */
    public MainCinemaFrame() {
        initComponents();
        
        // delete after
        Login(Optional.of(new User(2, "", ""))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cinestar kina s 5 zvjezdica *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCinemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCinemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCinemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCinemaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                MainCinemaFrame mainFrame = new MainCinemaFrame();
                
                // delete and uncoment 
                mainFrame.setVisible(true);
                
//                LoginForm form = new LoginForm(mainFrame);
//                form.setVisible(true);
            }
        });
    }

    @Override
    public void Login(Optional<User> user) {
        if (user.isPresent()) {
            idUser = user.get().getId();
            this.setVisible(true);
            init();
        }
    }

    private void init() {
        repository = RepositoryFactory.getUsersRepository();
        roleManager = (RoleManager) repository;
        configurePanels();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void configurePanels() {
        try {
            if (roleManager.isUserInRole(idUser, Role.ADMIN)) {
                tpContent.add("Admin", new AdminPanel());
            }
            tpContent.add("Movies", new MoviePanel());
        } catch (Exception ex) {
            Logger.getLogger(MainCinemaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
